package com.scriptsentries.model.enums;


public enum RiskSubCategory {
    // FACT_BASED_ISSUES
    DEFAMATION,
    FALSE_LIGHT,
    REAL_EVENTS,
    COMPOSITE_CHARACTERS,

    // GOVERNMENT
    GOVERNMENT_AGENCY,
    LAW_ENFORCEMENT,
    MILITARY,
    POLITICAL_FIGURES,

    // LIKENESS
    REAL_PERSON_LIVING,
    REAL_PERSON_DECEASED,
    CELEBRITY_LIKENESS,
    ATHLETE,

    // LOCATIONS
    REAL_LOCATION,
    PRIVATE_PROPERTY,
    LANDMARK,
    BUSINESS_ESTABLISHMENT,

    // MARKETING_ADDED_VALUE
    PRODUCT_PLACEMENT,
    BRAND_INTEGRATION,
    SPONSORED_CONTENT,

    // MUSIC_CHOREOGRAPHY
    SONG_LYRICS,
    MUSICAL_COMPOSITION,
    CHOREOGRAPHY,
    COVER_SONG,

    // NAMES_NUMBERS
    PHONE_NUMBER,
    ADDRESS,
    WEBSITE_URL,
    PERSONAL_NAME,
    COMPANY_NAME,

    // PLAYBACK
    TV_SHOW_CLIP,
    FILM_CLIP,
    NEWS_FOOTAGE,
    LOGO_ON_SCREEN,

    // PRODUCT_MISUSE
    BRAND_NEGATIVE_CONTEXT,
    PRODUCT_AS_WEAPON,
    PRODUCT_WITH_DRUGS,
    PRODUCT_DISPARAGEMENT,

    // PROPS_SET_DRESSING
    BRANDED_PROP,
    ARTWORK,
    BOOK_TITLE,
    MAGAZINE,

    // REFERENCES
    COPYRIGHTED_REFERENCE,
    TRADEMARKED_PHRASE,
    CULTURAL_REFERENCE,

    // VEHICLES
    VEHICLE_BRAND,
    LICENSE_PLATE,
    AIRCRAFT,
    WATERCRAFT,

    // WARDROBE
    DESIGNER_CLOTHING,
    BRANDED_APPAREL,
    SPORTS_UNIFORM,
    MILITARY_UNIFORM,

    // OTHER
    GENERAL_IP_CONCERN,
    UNKNOWN
}
